/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package twitter;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class AttributesDetails extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5442479358322390289L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AttributesDetails\",\"namespace\":\"twitter\",\"fields\":[]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Creates a new AttributesDetails RecordBuilder.
   * @return A new AttributesDetails RecordBuilder
   */
  public static twitter.AttributesDetails.Builder newBuilder() {
    return new twitter.AttributesDetails.Builder();
  }

  /**
   * Creates a new AttributesDetails RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AttributesDetails RecordBuilder
   */
  public static twitter.AttributesDetails.Builder newBuilder(twitter.AttributesDetails.Builder other) {
    return new twitter.AttributesDetails.Builder(other);
  }

  /**
   * Creates a new AttributesDetails RecordBuilder by copying an existing AttributesDetails instance.
   * @param other The existing instance to copy.
   * @return A new AttributesDetails RecordBuilder
   */
  public static twitter.AttributesDetails.Builder newBuilder(twitter.AttributesDetails other) {
    return new twitter.AttributesDetails.Builder(other);
  }

  /**
   * RecordBuilder for AttributesDetails instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AttributesDetails>
    implements org.apache.avro.data.RecordBuilder<AttributesDetails> {


    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(twitter.AttributesDetails.Builder other) {
      super(other);
    }

    /**
     * Creates a Builder by copying an existing AttributesDetails instance
     * @param other The existing instance to copy.
     */
    private Builder(twitter.AttributesDetails other) {
            super(SCHEMA$);
    }

    @Override
    public AttributesDetails build() {
      try {
        AttributesDetails record = new AttributesDetails();
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
